save_dir: 'saved_models/sdn_fir6_16kHz_sim_center_train'
fig_dir:  'figures/sdn_fir6_16kHz_sim_center_train'

sr: 16000
c: 343.0
source_index: 0
dataset_type: "simulated"

training:
  split_mode: concentric_square
  train_square_size: 4     # center 4x4 → train, outer border → val
  batch_size: 4
  accumulation_factor: 4
  val_accumulation_factor: 2
  n_epochs: 300
  learning_rate: 0.01
  lambda_edc: 0.5
  lambda_edp: 1.0
  lambda_edr: 1.0

sdn:
  N: 6
  junction_type: 'householder'
  fir_order: 6
  alpha: 0.22